### ISSUE TITLE
fix scrolling

### ISSUE THREAD

**Issue by danielcurtin** [danielcurtin/whats-cookin#59]
Our scroll bar on the card section is not working as intended - we should either take a step back and reevaluate or look for a fix

**Comment by chrissycooper** [comment]
Some thoughts after testing that might help troubleshoot: Is the issue the difference between scrolling with a scroll wheel and scrolling on a touchpad on our laptops? I have a very different issue when I use my mouse, it scrolls extremely slowly and I end up just clicking and dragging the bar. If I use my touchpad on the mac, I see better what Cass was saying in the feedback: when I scroll forward it works fine, but when I try to scroll backward, it awkwardly "corrects" where I scroll.
